#!/usr/bin/env /bin/sh
set -eu

echo "> starting pre-commit"

tmp_go_files=

cleanup() {
  if [ -n "${tmp_go_files}" ]; then
    rm -f "${tmp_go_files}"
  fi
}

trap cleanup EXIT HUP INT TERM

tmp_go_files=$(mktemp "./tmp-pre-commit-go-files.XXXXXX")

{
  git diff --name-only -z --diff-filter=ACMRTUXB -- '*.go'
  git ls-files --others --exclude-standard -z -- '*.go'
} > "${tmp_go_files}"

if [ -s "${tmp_go_files}" ]; then
  printf "> formatting these files\n"
  tr '\0' '\n' < "${tmp_go_files}"

  xargs -0 golangci fmt --verbose < "${tmp_go_files}"
fi

echo "> pre-commit done"
