services:
  redis:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - "redis_data:/data/"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "$PWD/dev/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - "$PWD/dev/rabbitmq/advanced.config:/etc/rabbitmq/advanced.config:ro"
      - rabbitmq_data:/var/lib/rabbitmq/

  pushgateway:
    command:
      - "--log.level=warn"
      - "--persistence.file=/pushgateway/persistence.store"
    environment:
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/pushgateway:latest
    restart: unless-stopped
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - pushgateway_data:/pushgateway/

  prometheus:
    command:
      ["--config.file=/etc/prometheus/prometheus.yml", "--log.level=warn"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/dev/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - prometheus_data:/var/lib/prometheus/
    depends_on:
      - pushgateway

  postgres:
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c 'SELECT 1'"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/dev/postgres/initdb.d/:/docker-entrypoint-initdb.d/:ro"
      - "$PWD/dev/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - postgres_data:/var/lib/postgresql/data/

  grafana:
    env_file:
      - .env
    environment:
      GF_ANALYTICS_DEFAULT_LANGUAGE: pt-BR
      GF_DATE_FORMATS_DEFAULT_TIMEZONE: "America/Sao_Paulo"
      GF_INTERNATIONALIZATION_ENABLED: true
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "$PWD/dev/grafana/provisioning/:/etc/grafana/provisioning/:ro"
      - "$PWD/dev/grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - grafana_data:/var/lib/grafana/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      pushgateway:
        condition: service_started
      redis:
        condition: service_started

volumes:
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  pushgateway_data:
    driver: local
  prometheus_data:
    driver: local
  postgres_data:
    driver: local
  grafana_data:
    driver: local
